package Pojo;
// Generated 7 Mar, 2021 12:51:36 PM by Hibernate Tools 4.3.1



/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {

     private long orderDetailsId;
     private String email;
     private String subject;
     private String body;
     private String userType;

    
    public OrderDetails() {
    }
    
    public OrderDetails(String email, String subject, String body,String userType) {
        this.email = email;
        this.subject = subject;
        this.body = body;
        this.userType = userType;
    }
     
     public long getOrderDetailsId() {
        return orderDetailsId;
    }

    public void setOrderDetailsId(long orderDetailsId) {
        this.orderDetailsId = orderDetailsId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }
    public String getUserType() {
        return userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }


}